### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by tlehman** [systemshift/memex#3]
I built this 4 weeks ago and started working on the same .mx repo file, but I am pretty sure there was data corruption so I nuked my repo. There should be a `memex --version` command, and some sort of internal check that makes sure the version that you are running is compatible with the repo file. If there are ever any known breaking changes, then have some sort of warning, or migration plan, so that this doesn't happen.

**Comment by systemshift** [comment]
https://github.com/systemshift/memex/commit/a156a2b7efc3f2116fdc4e60f71bce2a7b4712f1 now does support versioning and binary releases
